export const distressPhrases: string[] = [
  'want to end it',
  'want to end my life',
  'want to die',
  'going to kill myself',
  'plan to kill myself',
  'planning to end',
  'no reason to live',
  'better off dead',
  'can\'t go on',
  'don\'t want to be here anymore',
  'don\'t want to exist',
  'no point in living',
  'ending it all',
  'ending it tonight',
  'ending things tonight',
  'ready to go',
  'goodbye letter',
  'suicide note',
  'final goodbye',
  'not going to be around',
  'won\'t be here tomorrow',
  'won\'t be around much longer',
  'take my own life',
  'taking my own life',
  'harm myself',
  'hurt myself',
  'cutting myself',
  'overdose',
  'jump off',
  'hang myself',
];
