import { useState } from 'react';

// Hero examples are served from companion WebP files generated by
// `tools/optimize-hero-examples.mjs`. The desktop grid renders three at ~280px
// (DPR=2 → ~560px target → 540px source), and mobile renders a single image
// at up to 360px (DPR=3 → ~1080px → 720px source — DPR=3 phones are rare).
// PNG fallback exists for any browser without WebP (universal since 2020).
const EXAMPLES = [
  { webp540: '/examples/hero-1-540.webp', webp720: '/examples/hero-1-720.webp', png: '/examples/hero-1.png' },
  { webp540: '/examples/hero-2-540.webp', webp720: '/examples/hero-2-720.webp', png: '/examples/hero-2.png' },
  { webp540: '/examples/hero-3-540.webp', webp720: '/examples/hero-3-720.webp', png: '/examples/hero-3.png' },
] as const;

export function HeroExamples() {
  const [mobileIndex] = useState(() => Math.floor(Math.random() * EXAMPLES.length));

  return (
    <div className="w-full max-w-2xl mx-auto">
      <div className="hidden lg:grid grid-cols-3 gap-4">
        {EXAMPLES.map((ex, i) => (
          <picture key={i}>
            <source type="image/webp" srcSet={ex.webp540} />
            <img
              src={ex.png}
              alt=""
              loading="eager"
              fetchPriority="high"
              width={540}
              height={540}
              className="w-full aspect-square rounded-xl object-cover"
            />
          </picture>
        ))}
      </div>
      <div className="lg:hidden flex justify-center">
        <picture>
          <source type="image/webp" srcSet={EXAMPLES[mobileIndex].webp720} />
          <img
            src={EXAMPLES[mobileIndex].png}
            alt=""
            loading="eager"
            fetchPriority="high"
            width={720}
            height={720}
            className="w-[280px] aspect-square rounded-xl object-cover"
          />
        </picture>
      </div>
    </div>
  );
}
