import { useState } from 'react';

// Hero examples are served from companion WebP files generated by
// `tools/optimize-hero-examples.mjs`. The desktop grid renders three at ~280px
// (DPR=2 → ~560px target → 540px source), and mobile renders a single image
// at up to 360px (DPR=3 → ~1080px → 720px source — DPR=3 phones are rare).
// PNG fallback exists for any browser without WebP (universal since 2020).
const EXAMPLES = [
  { webp540: '/examples/hero-1-540.webp', webp720: '/examples/hero-1-720.webp', png: '/examples/hero-1.png' },
  { webp540: '/examples/hero-2-540.webp', webp720: '/examples/hero-2-720.webp', png: '/examples/hero-2.png' },
  { webp540: '/examples/hero-3-540.webp', webp720: '/examples/hero-3-720.webp', png: '/examples/hero-3.png' },
] as const;

const DESKTOP_BREAKPOINT_QUERY = '(min-width: 1024px)';

// Snapshot the matchMedia result once at mount instead of relying on
// `hidden lg:grid` / `lg:hidden` CSS to suppress the wrong viewport's
// `<img>`. Pre-fix, both viewport branches rendered into the DOM and
// the unwanted set was hidden via display:none — but `loading="eager"
// fetchPriority="high"` overrides Chrome/Firefox's display:none-skip
// optimization in some versions, and Safari fetches all `<img>` regardless
// of CSS. The result was that a mobile user fetched ~210 KB of desktop
// hero WebPs (3 × 540-wide) on top of the ~75 KB mobile WebP, and a
// desktop user fetched the unused mobile WebP on top of the desktop
// trio. With the JS-driven branch we render exactly the markup the
// viewport needs — no wasted bandwidth, no hidden-image fetches, no
// browser-quirk dependencies. Audit run 37/001.
//
// We pick the breakpoint ONCE at mount via useState's lazy initializer
// rather than subscribing to matchMedia changes. Reasons:
//   1) The user almost never resizes across 1024px during a page view.
//   2) If they do, the existing PosterCanvas resize handler is the only
//      reactive layout in the app — keeping HeroExamples sticky avoids
//      a network re-fetch on every breakpoint cross.
//   3) The first paint is what matters; remounting hero markup on resize
//      would produce a worse experience (image flash) for an edge case.
function detectIsDesktop(): boolean {
  if (typeof window === 'undefined' || typeof window.matchMedia !== 'function') {
    // SSR / hostile environment fallback — render the lighter mobile set
    // by default so a misconfigured environment doesn't waste bandwidth.
    return false;
  }
  return window.matchMedia(DESKTOP_BREAKPOINT_QUERY).matches;
}

export function HeroExamples() {
  const [isDesktop] = useState(detectIsDesktop);
  const [mobileIndex] = useState(() => Math.floor(Math.random() * EXAMPLES.length));

  if (isDesktop) {
    return (
      <div className="w-full max-w-2xl mx-auto">
        <div className="grid grid-cols-3 gap-4">
          {EXAMPLES.map((ex, i) => (
            <picture key={i}>
              <source type="image/webp" srcSet={ex.webp540} />
              <img
                src={ex.png}
                alt=""
                loading="eager"
                fetchPriority="high"
                width={540}
                height={540}
                className="w-full aspect-square rounded-xl object-cover"
              />
            </picture>
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="w-full max-w-2xl mx-auto">
      <div className="flex justify-center">
        <picture>
          <source type="image/webp" srcSet={EXAMPLES[mobileIndex].webp720} />
          <img
            src={EXAMPLES[mobileIndex].png}
            alt=""
            loading="eager"
            fetchPriority="high"
            width={720}
            height={720}
            className="w-[280px] aspect-square rounded-xl object-cover"
          />
        </picture>
      </div>
    </div>
  );
}
